
export class Audit {
  constructor(public id?: string,
              public username?: string,
              public loginDate?: any,
              public dateAction?: any,
              public uploadFileName?: string,
              public errorFileName?: string,
              public reportFileName?: string,
              public individuReportCSV?: string,
              public salarieReportCSV?: string,
              public contactReportCSV?: string,
              public paymentReportCSV?: string,
              public adresseReportCSV?: string,
              public compteReportCSV?: string,
              public updateIndividu?: string,
              public updateSalarie?: string,
              public updateContact?: string,
              public updatePayment?: string,
              public updateAdresse?: string,
              public updateCompte?: string,
              public deleteIndividu?: string,
              public deleteSalarie?: string,
              public deleteContact?: string,
              public deletePayment?: string,
              public deleteAdresse?: string,
              public deleteCompte?: string,
              public habilitation?: string,
              public createUser?: string,
              public updateUser?: string,
              public deleteUser?: string,
              public updateMouvement?: string,
              public deleteMouvement?: string,
              public updatePosition?: string,
              public deletePosition?: string,
              public uploadMovementFile?: string,
              public uploadPositionFile?: string,
              public exportMovementCSV?: string,
              public exportPositionCSV?: string,
              public operations?: string){}

}
