export const COUNTRY = [
    {name: 'Afghanistan', code: 'AFG'},
    {name: 'Åland Islands', code: 'ALA'},
    {name: 'Albania', code: 'ALB'},
    {name: 'Algeria', code: 'DZA'},
    {name: 'American Samoa', code: 'ASM'},
    {name: 'AndorrA', code: 'AND'},
    {name: 'Angola', code: 'AGO'},
    {name: 'Anguilla', code: 'AIA'},
    {name: 'Antarctica', code: 'ATA'},
    {name: 'Antigua and Barbuda', code: 'ATG'},
    {name: 'Argentina', code: 'ARG'},
    {name: 'Armenia', code: 'ARM'},
    {name: 'Aruba', code: 'ABW'},
    {name: 'Australia', code: 'AUS'},
    {name: 'Austria', code: 'AUT'},
    {name: 'Azerbaijan', code: 'AZE'},
    {name: 'Bahamas', code: 'BHS'},
    {name: 'Bahrain', code: 'BHR'},
    {name: 'Bangladesh', code: 'BGD'},
    {name: 'Barbados', code: 'BRB'},
    {name: 'Belarus', code: 'BLR'},
    {name: 'Belgium', code: 'BEL'},
    {name: 'Belize', code: 'BLZ'},
    {name: 'Benin', code: 'BEN'},
    {name: 'Bermuda', code: 'BMU'},
    {name: 'Bhutan', code: 'BTN'},
    {name: 'Bolivia', code: 'BOL'},
    {name: 'Bosnia and Herzegovina', code: 'BIH'},
    {name: 'Botswana', code: 'BWA'},
    {name: 'Bouvet Island', code: 'BVT'},
    {name: 'Brazil', code: 'BRA'},
    {name: 'British Indian Ocean Territory', code: 'IOT'},
    {name: 'Brunei Darussalam', code: 'BRN'},
    {name: 'Bulgaria', code: 'BGR'},
    {name: 'Burkina Faso', code: 'BFA'},
    {name: 'Burundi', code: 'BDI'},
    {name: 'Cambodia', code: 'KHM'},
    {name: 'Cameroon', code: 'CMR'},
    {name: 'Canada', code: 'CAN'},
    {name: 'Cape Verde', code: 'CPV'},
    {name: 'Cayman Islands', code: 'CYM'},
    {name: 'Central African Republic', code: 'CAF'},
    {name: 'Chad', code: 'TCD'},
    {name: 'Chile', code: 'CHL'},
    {name: 'China', code: 'CHN'},
    {name: 'Christmas Island', code: 'CXR'},
    {name: 'Cocos (Keeling) Islands', code: 'CCK'},
    {name: 'Colombia', code: 'COL'},
    {name: 'Comoros', code: 'COM'},
    {name: 'Congo', code: 'COG'},
    {name: 'Congo The Democratic Republic', code: 'COD'},
    {name: 'Cook Islands', code: 'COK'},
    {name: 'Costa Rica', code: 'CRI'},
    {name: 'Cote D\'Ivoire', code: 'CIV'},
    {name: 'Croatia', code: 'HRV'},
    {name: 'Cuba', code: 'CUB'},
    {name: 'Cyprus', code: 'CYP'},
    {name: 'Czech Republic', code: 'CZE'},
    {name: 'Denmark', code: 'DNK'},
    {name: 'Djibouti', code: 'DJI'},
    {name: 'Dominica', code: 'DMA'},
    {name: 'Dominican Republic', code: 'DOM'},
    {name: 'Ecuador', code: 'ECU'},
    {name: 'Egypt', code: 'EGY'},
    {name: 'El Salvador', code: 'SLV'},
    {name: 'Equatorial Guinea', code: 'GNQ'},
    {name: 'Eritrea', code: 'ERI'},
    {name: 'Estonia', code: 'EST'},
    {name: 'Ethiopia', code: 'ETH'},
    {name: 'Falkland Islands (Malvinas)', code: 'FLK'},
    {name: 'Faroe Islands', code: 'FRO'},
    {name: 'Fiji', code: 'FJI'},
    {name: 'Finland', code: 'FIN'},
    {name: 'France', code: 'FRA'},
    {name: 'French Guiana', code: 'GUF'},
    {name: 'French Polynesia', code: 'PYF'},
    {name: 'French Southern Territories', code: 'ATF'},
    {name: 'Gabon', code: 'GAB'},
    {name: 'Gambia', code: 'GMB'},
    {name: 'Georgia', code: 'GEO'},
    {name: 'Germany', code: 'DEU'},
    {name: 'Ghana', code: 'GHA'},
    {name: 'Gibraltar', code: 'GIB'},
    {name: 'Greece', code: 'GRC'},
    {name: 'Greenland', code: 'GRL'},
    {name: 'Grenada', code: 'GRD'},
    {name: 'Guadeloupe', code: 'GLP'},
    {name: 'Guam', code: 'GUM'},
    {name: 'Guatemala', code: 'GTM'},
    {name: 'Guernsey', code: 'GGY'},
    {name: 'Guinea', code: 'GIN'},
    {name: 'Guinea-Bissau', code: 'GNB'},
    {name: 'Guyana', code: 'GUY'},
    {name: 'Haiti', code: 'HTI'},
    {name: 'Heard Island and Mcdonald Islands', code: 'HMD'},
    {name: 'Holy See (Vatican City State)', code: 'VAT'},
    {name: 'Honduras', code: 'HND'},
    {name: 'Hong Kong', code: 'HKG'},
    {name: 'Hungary', code: 'HUN'},
    {name: 'Iceland', code: 'ISL'},
    {name: 'India', code: 'IND'},
    {name: 'Indonesia', code: 'IDN'},
    {name: 'Iran, Islamic Republic Of', code: 'IRN'},
    {name: 'Iraq', code: 'IRQ'},
    {name: 'Ireland', code: 'IRL'},
    {name: 'Isle of Man', code: 'IMN'},
    {name: 'Israel', code: 'ISR'},
    {name: 'Italy', code: 'ITA'},
    {name: 'Jamaica', code: 'JAM'},
    {name: 'Japan', code: 'JPN'},
    {name: 'Jersey', code: 'JEY'},
    {name: 'Jordan', code: 'JOR'},
    {name: 'Kazakhstan', code: 'KAZ'},
    {name: 'Kenya', code: 'KEN'},
    {name: 'Kiribati', code: 'KIR'},
    {name: 'Korea, Democratic People\'S Republic of', code: 'PRK'},
    {name: 'Korea, Republic of', code: 'KOR'},
    {name: 'Kuwait', code: 'KWT'},
    {name: 'Kyrgyzstan', code: 'KGZ'},
    {name: 'Lao People\'S Democratic Republic', code: 'LAO'},
    {name: 'Latvia', code: 'LVA'},
    {name: 'Lebanon', code: 'LBN'},
    {name: 'Lesotho', code: 'LSO'},
    {name: 'Liberia', code: 'LBR'},
    {name: 'Libyan Arab Jamahiriya', code: 'LBY'},
    {name: 'Liechtenstein', code: 'LIE'},
    {name: 'Lithuania', code: 'LTU'},
    {name: 'Luxembourg', code: 'LUX'},
    {name: 'Macao', code: 'MAC'},
    {name: 'Macedonia, The Former Yugoslav Republic of', code: 'MKD'},
    {name: 'Madagascar', code: 'MDG'},
    {name: 'Malawi', code: 'MWI'},
    {name: 'Malaysia', code: 'MYS'},
    {name: 'Maldives', code: 'MDV'},
    {name: 'Mali', code: 'MLI'},
    {name: 'Malta', code: 'MLT'},
    {name: 'Marshall Islands', code: 'MHL'},
    {name: 'Martinique', code: 'MTQ'},
    {name: 'Mauritania', code: 'MRT'},
    {name: 'Mauritius', code: 'MUS'},
    {name: 'Mayotte', code: 'MYT'},
    {name: 'Mexico', code: 'MEX'},
    {name: 'Micronesia, Federated States of', code: 'FSM'},
    {name: 'Moldova, Republic of', code: 'MDA'},
    {name: 'Monaco', code: 'MCO'},
    {name: 'Mongolia', code: 'MNG'},
    {name: 'Montserrat', code: 'MSR'},
    {name: 'Morocco', code: 'MAR'},
    {name: 'Mozambique', code: 'MOZ'},
    {name: 'Myanmar', code: 'MM'},
    {name: 'Namibia', code: 'NA'},
    {name: 'Nauru', code: 'NR'},
    {name: 'Nepal', code: 'NP'},
    {name: 'Netherlands', code: 'NL'},
    {name: 'Netherlands Antilles', code: 'AN'},
    {name: 'New Caledonia', code: 'NC'},
    {name: 'New Zealand', code: 'NZ'},
    {name: 'Nicaragua', code: 'NI'},
    {name: 'Niger', code: 'NE'},
    {name: 'Nigeria', code: 'NG'},
    {name: 'Niue', code: 'NU'},
    {name: 'Norfolk Island', code: 'NF'},
    {name: 'Northern Mariana Islands', code: 'MP'},
    {name: 'Norway', code: 'NO'},
    {name: 'Oman', code: 'OM'},
    {name: 'Pakistan', code: 'PK'},
    {name: 'Palau', code: 'PW'},
    {name: 'Palestinian Territory, Occupied', code: 'PS'},
    {name: 'Panama', code: 'PA'},
    {name: 'Papua New Guinea', code: 'PG'},
    {name: 'Paraguay', code: 'PY'},
    {name: 'Peru', code: 'PE'},
    {name: 'Philippines', code: 'PH'},
    {name: 'Pitcairn', code: 'PN'},
    {name: 'Poland', code: 'PL'},
    {name: 'Portugal', code: 'PT'},
    {name: 'Puerto Rico', code: 'PR'},
    {name: 'Qatar', code: 'QA'},
    {name: 'Reunion', code: 'RE'},
    {name: 'Romania', code: 'RO'},
    {name: 'Russian Federation', code: 'RU'},
    {name: 'RWANDA', code: 'RW'},
    {name: 'Saint Helena', code: 'SH'},
    {name: 'Saint Kitts and Nevis', code: 'KN'},
    {name: 'Saint Lucia', code: 'LC'},
    {name: 'Saint Pierre and Miquelon', code: 'PM'},
    {name: 'Saint Vincent and the Grenadines', code: 'VC'},
    {name: 'Samoa', code: 'WS'},
    {name: 'San Marino', code: 'SM'},
    {name: 'Sao Tome and Principe', code: 'ST'},
    {name: 'Saudi Arabia', code: 'SA'},
    {name: 'Senegal', code: 'SN'},
    {name: 'Serbia and Montenegro', code: 'CS'},
    {name: 'Seychelles', code: 'SC'},
    {name: 'Sierra Leone', code: 'SL'},
    {name: 'Singapore', code: 'SG'},
    {name: 'Slovakia', code: 'SK'},
    {name: 'Slovenia', code: 'SI'},
    {name: 'Solomon Islands', code: 'SB'},
    {name: 'Somalia', code: 'SO'},
    {name: 'South Africa', code: 'ZA'},
    {name: 'South Georgia and the South Sandwich Islands', code: 'GS'},
    {name: 'Spain', code: 'ES'},
    {name: 'Sri Lanka', code: 'LK'},
    {name: 'Sudan', code: 'SD'},
    {name: 'Suriname', code: 'SR'},
    {name: 'Svalbard and Jan Mayen', code: 'SJ'},
    {name: 'Swaziland', code: 'SZ'},
    {name: 'Sweden', code: 'SE'},
    {name: 'Switzerland', code: 'CH'},
    {name: 'Syrian Arab Republic', code: 'SY'},
    {name: 'Taiwan, Province of China', code: 'TW'},
    {name: 'Tajikistan', code: 'TJ'},
    {name: 'Tanzania, United Republic of', code: 'TZ'},
    {name: 'Thailand', code: 'TH'},
    {name: 'Timor-Leste', code: 'TL'},
    {name: 'Togo', code: 'TG'},
    {name: 'Tokelau', code: 'TK'},
    {name: 'Tonga', code: 'TO'},
    {name: 'Trinidad and Tobago', code: 'TT'},
    {name: 'Tunisia', code: 'TN'},
    {name: 'Turkey', code: 'TR'},
    {name: 'Turkmenistan', code: 'TM'},
    {name: 'Turks and Caicos Islands', code: 'TC'},
    {name: 'Tuvalu', code: 'TV'},
    {name: 'Uganda', code: 'UG'},
    {name: 'Ukraine', code: 'UA'},
    {name: 'United Arab Emirates', code: 'AE'},
    {name: 'United Kingdom', code: 'GB'},
    {name: 'United States', code: 'US'},
    {name: 'United States Minor Outlying Islands', code: 'UM'},
    {name: 'Uruguay', code: 'UY'},
    {name: 'Uzbekistan', code: 'UZ'},
    {name: 'Vanuatu', code: 'VU'},
    {name: 'Venezuela', code: 'VE'},
    {name: 'Viet Nam', code: 'VN'},
    {name: 'Virgin Islands, British', code: 'VG'},
    {name: 'Virgin Islands, U.S.', code: 'VI'},
    {name: 'Wallis and Futuna', code: 'WF'},
    {name: 'Western Sahara', code: 'EH'},
    {name: 'Yemen', code: 'YE'},
    {name: 'Zambia', code: 'ZM'},
    {name: 'Zimbabwe', code: 'ZW'}
  ] ;


